apiVersion: batch/v1
kind: Job
metadata:
  name: finetune-nf4-job
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: nvidia.com/gpu.product
                  operator: In
                  values:
                  - NVIDIA-A10
      containers:
      - name: nf4-container
        image: pytorch/pytorch:2.0.1-cuda11.7-cudnn8-runtime
        command: ["/bin/bash","-c"]
        args: ["pip install -U -r /qlora/qlora/requirements.txt; pip install -e /qlora/lm-evaluation-harness;
                python /qlora/lm-evaluation-harness/main.py --model hf-causal-experimental --model_args pretrained=huggyllama/llama-7b,peft=/qlora/finetune/nf4/checkpoint-1875/adapter_model,load_in_4bit=True,dtype=bfloat16,bnb_4bit_compute_dtype=bfloat16,bnb_4bit_quant_type=\u0027nf4\u0027 --tasks hendrycksTest-abstract_algebra,hendrycksTest-anatomy,hendrycksTest-astronomy,hendrycksTest-business_ethics,hendrycksTest-clinical_knowledge,hendrycksTest-college_biology,hendrycksTest-college_chemistry,hendrycksTest-college_computer_science,hendrycksTest-college_mathematics,hendrycksTest-college_medicine,hendrycksTest-college_physics,hendrycksTest-computer_security,hendrycksTest-conceptual_physics,hendrycksTest-econometrics,hendrycksTest-electrical_engineering,hendrycksTest-elementary_mathematics,hendrycksTest-formal_logic,hendrycksTest-global_facts,hendrycksTest-high_school_biology,hendrycksTest-high_school_chemistry,hendrycksTest-high_school_computer_science,hendrycksTest-high_school_european_history,hendrycksTest-high_school_geography,hendrycksTest-high_school_government_and_politics,hendrycksTest-high_school_macroeconomics,hendrycksTest-high_school_mathematics,hendrycksTest-high_school_microeconomics,hendrycksTest-high_school_physics,hendrycksTest-high_school_psychology,hendrycksTest-high_school_statistics,hendrycksTest-high_school_us_history,hendrycksTest-high_school_world_history,hendrycksTest-human_aging,hendrycksTest-human_sexuality,hendrycksTest-international_law,hendrycksTest-jurisprudence,hendrycksTest-logical_fallacies,hendrycksTest-machine_learning,hendrycksTest-management,hendrycksTest-marketing,hendrycksTest-medical_genetics,hendrycksTest-miscellaneous,hendrycksTest-moral_disputes,hendrycksTest-moral_scenarios,hendrycksTest-nutrition,hendrycksTest-philosophy,hendrycksTest-prehistory,hendrycksTest-professional_accounting,hendrycksTest-professional_law,hendrycksTest-professional_medicine,hendrycksTest-professional_psychology,hendrycksTest-public_relations,hendrycksTest-security_studies,hendrycksTest-sociology,hendrycksTest-us_foreign_policy,hendrycksTest-virology,hendrycksTest-world_religions --num_fewshot 5 --batch_size 1 --device cuda:0 --output_path /qlora/jensen/finetune_nf4_log.txt;
                "]
        volumeMounts:
        - mountPath: /qlora
          name: qlora-volume
        resources:
          limits:
            nvidia.com/gpu: "1"
            memory: "24G"
            cpu: "4"
          requests:
            nvidia.com/gpu: "1"
            memory: "24G"
            cpu: "4"
      - name: nf4dq-container
        image: pytorch/pytorch:2.0.1-cuda11.7-cudnn8-runtime
        command: ["/bin/bash","-c"]
        args: ["pip install -U -r /qlora/qlora/requirements.txt; pip install -e /qlora/lm-evaluation-harness;
                python /qlora/lm-evaluation-harness/main.py --model hf-causal-experimental --model_args pretrained=huggyllama/llama-7b,peft=/qlora/finetune/dq_nf4/checkpoint-1875/adapter_model,load_in_4bit=True,dtype=bfloat16,bnb_4bit_compute_dtype=bfloat16,bnb_4bit_quant_type=\u0027nf4\u0027,bnb_4bit_use_double_quant=True --tasks hendrycksTest-abstract_algebra,hendrycksTest-anatomy,hendrycksTest-astronomy,hendrycksTest-business_ethics,hendrycksTest-clinical_knowledge,hendrycksTest-college_biology,hendrycksTest-college_chemistry,hendrycksTest-college_computer_science,hendrycksTest-college_mathematics,hendrycksTest-college_medicine,hendrycksTest-college_physics,hendrycksTest-computer_security,hendrycksTest-conceptual_physics,hendrycksTest-econometrics,hendrycksTest-electrical_engineering,hendrycksTest-elementary_mathematics,hendrycksTest-formal_logic,hendrycksTest-global_facts,hendrycksTest-high_school_biology,hendrycksTest-high_school_chemistry,hendrycksTest-high_school_computer_science,hendrycksTest-high_school_european_history,hendrycksTest-high_school_geography,hendrycksTest-high_school_government_and_politics,hendrycksTest-high_school_macroeconomics,hendrycksTest-high_school_mathematics,hendrycksTest-high_school_microeconomics,hendrycksTest-high_school_physics,hendrycksTest-high_school_psychology,hendrycksTest-high_school_statistics,hendrycksTest-high_school_us_history,hendrycksTest-high_school_world_history,hendrycksTest-human_aging,hendrycksTest-human_sexuality,hendrycksTest-international_law,hendrycksTest-jurisprudence,hendrycksTest-logical_fallacies,hendrycksTest-machine_learning,hendrycksTest-management,hendrycksTest-marketing,hendrycksTest-medical_genetics,hendrycksTest-miscellaneous,hendrycksTest-moral_disputes,hendrycksTest-moral_scenarios,hendrycksTest-nutrition,hendrycksTest-philosophy,hendrycksTest-prehistory,hendrycksTest-professional_accounting,hendrycksTest-professional_law,hendrycksTest-professional_medicine,hendrycksTest-professional_psychology,hendrycksTest-public_relations,hendrycksTest-security_studies,hendrycksTest-sociology,hendrycksTest-us_foreign_policy,hendrycksTest-virology,hendrycksTest-world_religions --num_fewshot 5 --batch_size 1 --device cuda:0 --output_path /qlora/jensen/finetune_nf4_dq_log.txt;
                "]
        volumeMounts:
        - mountPath: /qlora
          name: qlora-volume
        resources:
          limits:
            nvidia.com/gpu: "1"
            memory: "24G"
            cpu: "4"
          requests:
            nvidia.com/gpu: "1"
            memory: "24G"
            cpu: "4"
      restartPolicy: Never
      volumes:
        - name: qlora-volume
          persistentVolumeClaim:
            claimName: qlora-volume
